routers:
  - hostname: Router1
    interfaces:
      - name: eth0
        ip_address: 192.168.1.1
        subnet_mask: 255.255.255.0
      - name: eth1
        ip_address: 192.168.1.2
        subnet_mask: 255.255.255.0
  - hostname: Router2
    interfaces:
      - name: eth0
        ip_address: 192.168.2.1
        subnet_mask: 255.255.255.0
      - name: eth1
        ip_address: 192.168.2.2
        subnet_mask: 255.255.255.0
